insert into public.products (name, category, unit, is_active)
values
  ('Arroz branco', 'alimentos_basicos', 'kg', true),
  ('Arroz integral', 'alimentos_basicos', 'kg', true),
  ('Massa esparguete', 'alimentos_basicos', 'emb.', true),
  ('Massa penne', 'alimentos_basicos', 'emb.', true),
  ('Feijao preto', 'alimentos_basicos', 'kg', true),
  ('Feijao branco', 'alimentos_basicos', 'kg', true),
  ('Grao de bico', 'alimentos_basicos', 'kg', true),
  ('Lentilhas', 'alimentos_basicos', 'kg', true),
  ('Farinha de trigo', 'alimentos_basicos', 'kg', true),
  ('Farinha integral', 'alimentos_basicos', 'kg', true),
  ('Acucar branco', 'alimentos_basicos', 'kg', true),
  ('Acucar mascavado', 'alimentos_basicos', 'kg', true),
  ('Sal', 'alimentos_basicos', 'kg', true),
  ('Azeite', 'alimentos_basicos', 'garrafa', true),
  ('Oleo vegetal', 'alimentos_basicos', 'garrafa', true),
  ('Leite meio gordo', 'laticinios', 'L', true),
  ('Leite magro', 'laticinios', 'L', true),
  ('Leite vegetal', 'laticinios', 'L', true),
  ('Iogurte natural', 'laticinios', 'pack', true),
  ('Iogurte grego', 'laticinios', 'pack', true),
  ('Queijo flamengo', 'laticinios', 'emb.', true),
  ('Queijo fatiado', 'laticinios', 'emb.', true),
  ('Queijo ralado', 'laticinios', 'emb.', true),
  ('Manteiga', 'laticinios', 'emb.', true),
  ('Margarina', 'laticinios', 'emb.', true),
  ('Natas', 'laticinios', 'pack', true),
  ('Peito de frango', 'proteinas', 'kg', true),
  ('Coxas de frango', 'proteinas', 'kg', true),
  ('Carne bovina', 'proteinas', 'kg', true),
  ('Carne picada', 'proteinas', 'kg', true),
  ('Carne suina', 'proteinas', 'kg', true),
  ('Costeletas de porco', 'proteinas', 'kg', true),
  ('Salmao', 'proteinas', 'kg', true),
  ('Pescada', 'proteinas', 'kg', true),
  ('Atum enlatado', 'proteinas', 'lata', true),
  ('Sardinha enlatada', 'proteinas', 'lata', true),
  ('Ovos (duzia)', 'proteinas', 'duzia', true),
  ('Banana', 'frutas', 'kg', true),
  ('Maca', 'frutas', 'kg', true),
  ('Pera', 'frutas', 'kg', true),
  ('Laranja', 'frutas', 'kg', true),
  ('Tangerina', 'frutas', 'kg', true),
  ('Manga', 'frutas', 'un', true),
  ('Abacate', 'frutas', 'un', true),
  ('Morango', 'frutas', 'emb.', true),
  ('Uva', 'frutas', 'kg', true),
  ('Kiwi', 'frutas', 'kg', true),
  ('Batata', 'legumes', 'kg', true),
  ('Batata doce', 'legumes', 'kg', true),
  ('Cenoura', 'legumes', 'kg', true),
  ('Cebola', 'legumes', 'kg', true),
  ('Alho', 'legumes', 'cabeca', true),
  ('Tomate', 'legumes', 'kg', true),
  ('Alface', 'legumes', 'un', true),
  ('Brocolos', 'legumes', 'un', true),
  ('Courgette', 'legumes', 'kg', true),
  ('Pimento', 'legumes', 'kg', true),
  ('Pao', 'padaria', 'un', true),
  ('Pao de forma', 'padaria', 'emb.', true),
  ('Pao integral', 'padaria', 'emb.', true),
  ('Croissant', 'padaria', 'un', true),
  ('Bolachas', 'padaria', 'emb.', true),
  ('Tostas', 'padaria', 'emb.', true),
  ('Agua mineral', 'bebidas', 'garrafa', true),
  ('Refrigerante cola', 'bebidas', 'garrafa', true),
  ('Sumo de laranja', 'bebidas', 'pack', true),
  ('Sumo multifrutas', 'bebidas', 'pack', true),
  ('Cafe', 'bebidas', 'emb.', true),
  ('Cha', 'bebidas', 'emb.', true),
  ('Cerveja', 'bebidas', 'pack', true),
  ('Vinho', 'bebidas', 'garrafa', true),
  ('Detergente loica', 'limpeza', 'emb.', true),
  ('Detergente roupa', 'limpeza', 'emb.', true),
  ('Amaciador', 'limpeza', 'emb.', true),
  ('Lixivia', 'limpeza', 'garrafa', true),
  ('Multiusos', 'limpeza', 'spray', true),
  ('Desinfetante', 'limpeza', 'emb.', true),
  ('Esponja', 'limpeza', 'pack', true),
  ('Pano de limpeza', 'limpeza', 'pack', true),
  ('Shampoo', 'higiene', 'emb.', true),
  ('Condicionador', 'higiene', 'emb.', true),
  ('Gel de banho', 'higiene', 'emb.', true),
  ('Sabonete', 'higiene', 'un', true),
  ('Pasta de dentes', 'higiene', 'un', true),
  ('Escova de dentes', 'higiene', 'un', true),
  ('Papel higienico', 'higiene', 'pack', true),
  ('Desodorizante', 'higiene', 'un', true),
  ('Legumes congelados', 'congelados', 'emb.', true),
  ('Pizza congelada', 'congelados', 'un', true),
  ('Batatas fritas congeladas', 'congelados', 'emb.', true),
  ('Peixe congelado', 'congelados', 'emb.', true),
  ('Hamburguer congelado', 'congelados', 'emb.', true),
  ('Gelado', 'congelados', 'un', true),
  ('Molho de tomate', 'mercearia', 'emb.', true),
  ('Ketchup', 'mercearia', 'emb.', true),
  ('Maionese', 'mercearia', 'emb.', true),
  ('Mostarda', 'mercearia', 'emb.', true),
  ('Cereais', 'mercearia', 'emb.', true),
  ('Chocolate', 'mercearia', 'un', true),
  ('Snacks', 'mercearia', 'emb.', true),
  ('Frutos secos', 'mercearia', 'emb.', true)
on conflict ((lower(name))) do update
set
  category = excluded.category,
  unit = excluded.unit,
  is_active = true;
